### ISSUE TITLE
erro no projeto?

### ISSUE THREAD

**Issue by theaudiodesigner** [jocimarjsc/blazebot#10]
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

**Comment by jocimarjsc** [comment]
> curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number

Esse erro não é do projeto, e sim da ferramenta utilizada para fazer a requisição, Creio que faltou passar o body da requisição exemplo:

curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://localhost:3000/colors
