### ISSUE TITLE
esta dando erro

### ISSUE THREAD

**Issue by DeyvissonSnuffs** [jocimarjsc/blazebot#12]
esta dando erro ou eu nao consegui fazer banco de dados
![image](https://user-images.githubusercontent.com/85204721/180624673-bba00093-9d41-47e1-b2ba-1d6ac09e5c99.png)

**Comment by jocimarjsc** [comment]
> esta dando erro ou eu nao consegui fazer banco de dados
> 
> ![image](https://user-images.githubusercontent.com/85204721/180624673-bba00093-9d41-47e1-b2ba-1d6ac09e5c99.png)
> 
> 

Como está seu arquivo .env?
