### ISSUE TITLE
Consigo criar uma rota automática para captura?

### ISSUE THREAD

**Issue by sonickbh** [jocimarjsc/blazebot#13]
Se sim qual parte do código ali seria responsável para receber ela teria que adicionar um webscrap? Da uma luz

**Comment by jocimarjsc** [comment]
> Se sim qual parte do código ali seria responsável para receber ela teria que adicionar um webscrap? Da uma luz

Vc pode criar um webscrap e enviar para a rota do bot. 

http://localhost:3000/colors

Envia no body da requisição o colorName e number
