### ISSUE TITLE
Versão premium

### ISSUE THREAD

**Issue by MarceIinn** [jocimarjsc/blazebot#2]
Você tem uma versão premium desse bot que possa ser vendida? tenho interesse de comprar.

**Comment by jocimarjsc** [comment]
> Você tem uma versão premium desse bot que possa ser vendida? tenho interesse de comprar.

Tenho uma em funcionamento com o padrão de um cliente, o que consigo fazer e alugar ele, e você passa o seu padrão para que eu coloque.

**Comment by MarceIinn** [comment]
> > Você tem uma versão premium desse bot que possa ser vendida? tenho interesse de comprar.
> 
> Tenho uma em funcionamento com o padrão de um cliente, o que consigo fazer e alugar ele, e você passa o seu padrão para que eu coloque.

como faço pra entrar em contato com você pra negociar?

**Comment by jocimarjsc** [comment]
> > > Você tem uma versão premium desse bot que possa ser vendida? tenho interesse de comprar.
> 
> > 
> 
> > Tenho uma em funcionamento com o padrão de um cliente, o que consigo fazer e alugar ele, e você passa o seu padrão para que eu coloque.
> 
> 
> 
> como faço pra entrar em contato com você pra negociar?

Chama no telegram @jocimarjsc
