### ISSUE TITLE
Cannot GET

### ISSUE THREAD

**Issue by JFProgrammer** [jocimarjsc/blazebot#4]
Poderia me ajudar com este error por favor?, faço tudo certo chega na parte da route "colors" não consigo acessar me retorna esse erro...

Cannot GET /colors

**Comment by joaohitho** [comment]
> Poderia me ajudar com este error por favor?, faço tudo certo chega na parte da route "colors" não consigo acessar me retorna esse erro...
> 
> Cannot GET /colors

Se trata de uma rota post, você deve passar o body com a ultima cor

**Comment by glmrstack** [comment]
Poderia dar um exemplo?

Passando a cor no body também dá isso.

**Comment by jocimarjsc** [comment]
Provavelmente está usando o método "GET" troque por "POST" e passe os seguintes parâmetros colorName E number. 


> Poderia me ajudar com este error por favor?, faço tudo certo chega na parte da route "colors" não consigo acessar me retorna esse erro...
> 
> 
> 
> Cannot GET /colors

**Comment by joaohitho** [comment]
> Provavelmente está usando o método "GET" troque por "POST" e passe os seguintes parâmetros colorName E number.
> 
> > Poderia me ajudar com este error por favor?, faço tudo certo chega na parte da route "colors" não consigo acessar me retorna esse erro...
> > Cannot GET /colors

Como configurar da maneira certa para o bot começar a enviar novas probabilidades?

**Comment by jocimarjsc** [comment]
> > Provavelmente está usando o método "GET" troque por "POST" e passe os seguintes parâmetros colorName E number.
> 
> > 
> 
> > > Poderia me ajudar com este error por favor?, faço tudo certo chega na parte da route "colors" não consigo acessar me retorna esse erro...
> 
> > > Cannot GET /colors
> 
> 
> 
> Como configurar da maneira certa para o bot começar a enviar novas probabilidades? 

Está no README do projeto

**Comment by DebugCrazY** [comment]
como eu consigo alterar o método get para post?

**Comment by DebugCrazY** [comment]
como eu faço pra enviar uma request?
