### ISSUE TITLE
Dúvida sobre padrões 

### ISSUE THREAD

**Issue by yosefben** [jocimarjsc/blazebot#5]
Oi o seu bot é legal, consegui fazer quase tudo, queria tirar uma dúvida como fazer os padrões automaticos no bot ele ficar rodando?
Obrigado por compartilhar o bot e ajudar nas nossas questões.

**Comment by jocimarjsc** [comment]
> Oi o seu bot é legal, consegui fazer quase tudo, queria tirar uma dúvida como fazer os padrões automaticos no bot ele ficar rodando?
> 
> Obrigado por compartilhar o bot e ajudar nas nossas questões. 

O padrão que tinha começado nesse projeto era padrão de cores mas vc pode codar da melhor forma que vc achar.
