### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by tazimania** [jocimarjsc/blazebot#6]
boa noite , poderia me ajudar no
![image](https://user-images.githubusercontent.com/108041280/175195237-c59946b6-70ff-4fde-befa-aad6f299f05f.png)
 meu erro com o bot, ele nao inicia como produçao ele começa a rodar e desliga sozinho mais quando dou o comando "npm run dev"ele roda normal ps: seu projeto ficou top parabems

**Comment by jocimarjsc** [comment]
> boa noite , poderia me ajudar no
> 
> ![image](https://user-images.githubusercontent.com/108041280/175195237-c59946b6-70ff-4fde-befa-aad6f299f05f.png)
> 
>  meu erro com o bot, ele nao inicia como produçao ele começa a rodar e desliga sozinho mais quando dou o comando "npm run dev"ele roda normal ps: seu projeto ficou top parabems

Após ter executado npm run build vc executou npm start?
