### ISSUE TITLE
Como funciona? 

### ISSUE THREAD

**Issue by Josebr1** [jocimarjsc/blazebot#7]
Como ele coleta os dados e qual o padrão que é utilizado para os próximos resultados? 
Não ficou claro.

**Comment by jocimarjsc** [comment]
> Como ele coleta os dados e qual o padrão que é utilizado para os próximos resultados? Não ficou claro.

Esse projeto não faz a coleta da cor e não existe um padrão em execução, esses dois itens é de responsabilidade de quem vai usar o projeto.
