### ISSUE TITLE
Poderia deixar um exemplo desse POST que deve ser enviado?

### ISSUE THREAD

**Issue by DinhoNunesLC** [jocimarjsc/blazebot#8]

**Comment by yosefben** [comment]
Ele pode usar o insomnia para ligar o banco e o bot.

**Comment by CentroEducacional-CEC** [comment]
Poderia deixar um exemplo dessa request que deve ser enviado para a url?

Você que fez o script sabe fazer, quem está aprendendo sobre, não consegue. É dificil responder corretamente a pergunta?

**Comment by DinhoNunesLC** [comment]
Deixa pra lá. Plataforma não funcionou, não tem o porquê perder tempo.

**Comment by jocimarjsc** [comment]
> Poderia deixar um exemplo dessa request que deve ser enviado para a url?
> 
> 
> 
> Você que fez o script sabe fazer, quem está aprendendo sobre, não consegue. É dificil responder corretamente a pergunta?
> 
> 
Foi o que eu fiz, falei o que tem que fazer, não precisa de script para fazer uma request, pode usar insomnia ou qualquer outro app que faça request a API.
