### ISSUE TITLE
Como adicionar novos padrões?

### ISSUE THREAD

**Issue by GMoreira05** [jocimarjsc/blazebot#9]
Olá, gostaria de saber como posso cadastrar um novo padrão, com um exemplo se possível. Grato!
Exemplo de padrão: 9, 8, 7, 0

Sempre q tiver 9, 8, 7 ele sugerir white

**Comment by CentroEducacional-CEC** [comment]
O padrão é de cores!
Não tem padrão de números!

**Comment by jocimarjsc** [comment]
> Olá, gostaria de saber como posso cadastrar um novo padrão, com um exemplo se possível. Grato!
> 
> Exemplo de padrão: 9, 8, 7, 0
> 
> 
> 
> Sempre q tiver 9, 8, 7 ele sugerir white

Para alterar o padrão você precisa alterar todo código desse arquivo 

./src/helpers/botMetrics/MetricDouble.ts

E colocar o padrão que precisa.

**Comment by yosefben** [comment]
Não teria como ter um arquivo externo json que contém as estratégias de cor?
 Então o código teria uma comparação o arquivo.

**Comment by jocimarjsc** [comment]
> Não teria como ter um arquivo externo json que contém as estratégias de cor?
> 
>  Então o código teria uma comparação o arquivo.

Essa estratégia de quantas cor precisar para poder enviar o sinal, você configura direto com seu bot no telegram, quando esse projeto estiver funcionando em seu pc, basta iniciar uma conversa com seu bot com esse comando /start e só seguir os passos.
